import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import Footer from "./(home)/_components/Footer";
import Provider from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const jost = Jost({
  variable: "--font-jost",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${jost.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Provider> {children}</Provider>
        <Footer />
      </body>
    </html>
  );
}
